export const pytania = [
{question: "Pierwsze pytanie: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},
{question: "Drugie pytanie: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem.",
answer1: "A: Nie wiem",
answer2: "B: Wiem",
answer3: "C: Tak",
answer4: "D: Nie",
},
{question: "Trzecie pytanie: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: 1",
answer2: "B: 2",
answer3: "C: 3",
answer4: "D: 4",
},
{question: "Czwarte pytanie: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem?",
answer2: "B: Ipsum?",
answer3: "C: Dolor?",
answer4: "D: Sit?",
},
{question: "Piąte pytanie jest bardzo krótkie",
answer1: "A: A",
answer2: "B: B",
answer3: "C: C",
answer4: "D: D",
},
{question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},
{question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},
{question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},
{question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},
{question: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam.",
answer1: "A: Lorem",
answer2: "B: Ipsum",
answer3: "C: Dolor",
answer4: "D: Sit",
},

];
